/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as JoinOurBenchRouteImport } from './routes/join-our-bench'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as MerchantPoliciesRouteImport } from './routes/merchant-policies'
import { Route as OfferCalibrationRouteImport } from './routes/offer-calibration'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as PodsRouteImport } from './routes/pods'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyCsgRouteImport } from './routes/why-csg'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GlobalDeliveryIndexRouteImport } from './routes/global-delivery.index'
import { Route as GlobalDeliveryRegionRouteImport } from './routes/global-delivery.$region'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StaffingIndexRouteImport } from './routes/staffing.index'
import { Route as StaffingSlugRouteImport } from './routes/staffing.$slug'
import { Route as StaffingPodsRouteImport } from './routes/staffing.pods'
import { Route as StaffingRolesRouteImport } from './routes/staffing.roles'
import { Route as StaffingSpecializedRolesRouteImport } from './routes/staffing.specialized-roles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinOurBenchRoute = JoinOurBenchRouteImport.update({
  id: '/join-our-bench',
  path: '/join-our-bench',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantPoliciesRoute = MerchantPoliciesRouteImport.update({
  id: '/merchant-policies',
  path: '/merchant-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferCalibrationRoute = OfferCalibrationRouteImport.update({
  id: '/offer-calibration',
  path: '/offer-calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PodsRoute = PodsRouteImport.update({
  id: '/pods',
  path: '/pods',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyCsgRoute = WhyCsgRouteImport.update({
  id: '/why-csg',
  path: '/why-csg',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalDeliveryIndexRoute = GlobalDeliveryIndexRouteImport.update({
  id: '/global-delivery/',
  path: '/global-delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalDeliveryRegionRoute = GlobalDeliveryRegionRouteImport.update({
  id: '/global-delivery/$region',
  path: '/global-delivery/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingIndexRoute = StaffingIndexRouteImport.update({
  id: '/staffing/',
  path: '/staffing/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingSlugRoute = StaffingSlugRouteImport.update({
  id: '/staffing/$slug',
  path: '/staffing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingPodsRoute = StaffingPodsRouteImport.update({
  id: '/staffing/pods',
  path: '/staffing/pods',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingRolesRoute = StaffingRolesRouteImport.update({
  id: '/staffing/roles',
  path: '/staffing/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingSpecializedRolesRoute =
  StaffingSpecializedRolesRouteImport.update({
    id: '/staffing/specialized-roles',
    path: '/staffing/specialized-roles',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/join-our-bench': typeof JoinOurBenchRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/merchant-policies': typeof MerchantPoliciesRoute
  '/offer-calibration': typeof OfferCalibrationRoute
  '/our-story': typeof OurStoryRoute
  '/pods': typeof PodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/why-csg': typeof WhyCsgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/global-delivery/$region': typeof GlobalDeliveryRegionRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staffing/$slug': typeof StaffingSlugRoute
  '/staffing/pods': typeof StaffingPodsRoute
  '/staffing/roles': typeof StaffingRolesRoute
  '/staffing/specialized-roles': typeof StaffingSpecializedRolesRoute
  '/blog/': typeof BlogIndexRoute
  '/global-delivery/': typeof GlobalDeliveryIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staffing/': typeof StaffingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/join-our-bench': typeof JoinOurBenchRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/merchant-policies': typeof MerchantPoliciesRoute
  '/offer-calibration': typeof OfferCalibrationRoute
  '/our-story': typeof OurStoryRoute
  '/pods': typeof PodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/why-csg': typeof WhyCsgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/global-delivery/$region': typeof GlobalDeliveryRegionRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staffing/$slug': typeof StaffingSlugRoute
  '/staffing/pods': typeof StaffingPodsRoute
  '/staffing/roles': typeof StaffingRolesRoute
  '/staffing/specialized-roles': typeof StaffingSpecializedRolesRoute
  '/blog': typeof BlogIndexRoute
  '/global-delivery': typeof GlobalDeliveryIndexRoute
  '/services': typeof ServicesIndexRoute
  '/staffing': typeof StaffingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/join-our-bench': typeof JoinOurBenchRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/merchant-policies': typeof MerchantPoliciesRoute
  '/offer-calibration': typeof OfferCalibrationRoute
  '/our-story': typeof OurStoryRoute
  '/pods': typeof PodsRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/why-csg': typeof WhyCsgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/global-delivery/$region': typeof GlobalDeliveryRegionRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/staffing/$slug': typeof StaffingSlugRoute
  '/staffing/pods': typeof StaffingPodsRoute
  '/staffing/roles': typeof StaffingRolesRoute
  '/staffing/specialized-roles': typeof StaffingSpecializedRolesRoute
  '/blog/': typeof BlogIndexRoute
  '/global-delivery/': typeof GlobalDeliveryIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/staffing/': typeof StaffingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/join-our-bench'
    | '/legal-notice'
    | '/merchant-policies'
    | '/offer-calibration'
    | '/our-story'
    | '/pods'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/why-csg'
    | '/blog/$slug'
    | '/global-delivery/$region'
    | '/services/$slug'
    | '/staffing/$slug'
    | '/staffing/pods'
    | '/staffing/roles'
    | '/staffing/specialized-roles'
    | '/blog/'
    | '/global-delivery/'
    | '/services/'
    | '/staffing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/join-our-bench'
    | '/legal-notice'
    | '/merchant-policies'
    | '/offer-calibration'
    | '/our-story'
    | '/pods'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/why-csg'
    | '/blog/$slug'
    | '/global-delivery/$region'
    | '/services/$slug'
    | '/staffing/$slug'
    | '/staffing/pods'
    | '/staffing/roles'
    | '/staffing/specialized-roles'
    | '/blog'
    | '/global-delivery'
    | '/services'
    | '/staffing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/get-started'
    | '/join-our-bench'
    | '/legal-notice'
    | '/merchant-policies'
    | '/offer-calibration'
    | '/our-story'
    | '/pods'
    | '/privacy'
    | '/refund'
    | '/terms'
    | '/why-csg'
    | '/blog/$slug'
    | '/global-delivery/$region'
    | '/services/$slug'
    | '/staffing/$slug'
    | '/staffing/pods'
    | '/staffing/roles'
    | '/staffing/specialized-roles'
    | '/blog/'
    | '/global-delivery/'
    | '/services/'
    | '/staffing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  JoinOurBenchRoute: typeof JoinOurBenchRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  MerchantPoliciesRoute: typeof MerchantPoliciesRoute
  OfferCalibrationRoute: typeof OfferCalibrationRoute
  OurStoryRoute: typeof OurStoryRoute
  PodsRoute: typeof PodsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  WhyCsgRoute: typeof WhyCsgRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GlobalDeliveryRegionRoute: typeof GlobalDeliveryRegionRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  StaffingSlugRoute: typeof StaffingSlugRoute
  StaffingPodsRoute: typeof StaffingPodsRoute
  StaffingRolesRoute: typeof StaffingRolesRoute
  StaffingSpecializedRolesRoute: typeof StaffingSpecializedRolesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GlobalDeliveryIndexRoute: typeof GlobalDeliveryIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StaffingIndexRoute: typeof StaffingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-our-bench': {
      id: '/join-our-bench'
      path: '/join-our-bench'
      fullPath: '/join-our-bench'
      preLoaderRoute: typeof JoinOurBenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-policies': {
      id: '/merchant-policies'
      path: '/merchant-policies'
      fullPath: '/merchant-policies'
      preLoaderRoute: typeof MerchantPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-calibration': {
      id: '/offer-calibration'
      path: '/offer-calibration'
      fullPath: '/offer-calibration'
      preLoaderRoute: typeof OfferCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pods': {
      id: '/pods'
      path: '/pods'
      fullPath: '/pods'
      preLoaderRoute: typeof PodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-csg': {
      id: '/why-csg'
      path: '/why-csg'
      fullPath: '/why-csg'
      preLoaderRoute: typeof WhyCsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-delivery/': {
      id: '/global-delivery/'
      path: '/global-delivery'
      fullPath: '/global-delivery/'
      preLoaderRoute: typeof GlobalDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-delivery/$region': {
      id: '/global-delivery/$region'
      path: '/global-delivery/$region'
      fullPath: '/global-delivery/$region'
      preLoaderRoute: typeof GlobalDeliveryRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing/': {
      id: '/staffing/'
      path: '/staffing'
      fullPath: '/staffing/'
      preLoaderRoute: typeof StaffingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing/$slug': {
      id: '/staffing/$slug'
      path: '/staffing/$slug'
      fullPath: '/staffing/$slug'
      preLoaderRoute: typeof StaffingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing/pods': {
      id: '/staffing/pods'
      path: '/staffing/pods'
      fullPath: '/staffing/pods'
      preLoaderRoute: typeof StaffingPodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing/roles': {
      id: '/staffing/roles'
      path: '/staffing/roles'
      fullPath: '/staffing/roles'
      preLoaderRoute: typeof StaffingRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing/specialized-roles': {
      id: '/staffing/specialized-roles'
      path: '/staffing/specialized-roles'
      fullPath: '/staffing/specialized-roles'
      preLoaderRoute: typeof StaffingSpecializedRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  JoinOurBenchRoute: JoinOurBenchRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  MerchantPoliciesRoute: MerchantPoliciesRoute,
  OfferCalibrationRoute: OfferCalibrationRoute,
  OurStoryRoute: OurStoryRoute,
  PodsRoute: PodsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  WhyCsgRoute: WhyCsgRoute,
  BlogSlugRoute: BlogSlugRoute,
  GlobalDeliveryRegionRoute: GlobalDeliveryRegionRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  StaffingSlugRoute: StaffingSlugRoute,
  StaffingPodsRoute: StaffingPodsRoute,
  StaffingRolesRoute: StaffingRolesRoute,
  StaffingSpecializedRolesRoute: StaffingSpecializedRolesRoute,
  BlogIndexRoute: BlogIndexRoute,
  GlobalDeliveryIndexRoute: GlobalDeliveryIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StaffingIndexRoute: StaffingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
